txt = fileread('new_lanelet2_maps.osm');

xTok = regexp(txt,...
    'k="local_x" v="([^"]+)"',...
    'tokens');

yTok = regexp(txt,...
    'k="local_y" v="([^"]+)"',...
    'tokens');

osmLocalX = cellfun(@(c) str2double(c{1}), xTok);
osmLocalY = cellfun(@(c) str2double(c{1}), yTok);

save('../results/osm_local.mat',...
    'osmLocalX','osmLocalY');
